### ISSUE TITLE
Meaning of blankCompOpt is not documented

### ISSUE THREAD

**Issue by raxod502** [haskell-hvr/regex-tdfa#13]
[The documentation for CompOption](http://hackage.haskell.org/package/regex-tdfa-1.2.3.1/docs/Text-Regex-TDFA.html#t:CompOption) details two different values for each field, one for defaultCompOpt and one for blankCompOpt. However, neither of these variables are documented. I assume that defaultCompOpt is used if you use one of the convenience functions to construct a regex from a string (although https://github.com/haskell-hvr/regex-tdfa/issues/11 makes me unsure of this), but I cannot see where blankCompOpt is used even in the code. Why are there two variables?

**Comment by andreasabel** [comment]
They are part of the `regex-base` package, see, e.g. https://hackage.haskell.org/package/regex-base-0.94.0.2/docs/Text-Regex-Base-RegexLike.html#v:blankCompOpt.
