### ISSUE TITLE
`getAllTextMatches` only delivers matches "on-the-money"

### ISSUE THREAD

**Issue by eppolito** [haskell-hvr/regex-tdfa#15]
Matching a string of repeated characters seems to confuse `getAllTextMatches`.  Minimal test case:

Input: `> getAllTextMatches ("aaa" =~ "aa") :: [String]`
Output: `["aa"]`
Expected `["aa","aa"]`

Input: `> getAllTextMatches ("aaaa" =~ "aa") :: [String]`
Output: `["aa","aa"]`
Expected `["aa","aa","aa"]`

I guess `getAllTextMatches` is removing the match before looking for additional matches.

**Comment by andreasabel** [comment]
This behavior conforms to what `Text.Regex.Posix` is doing, so I am inclined to consider this _working as intended_.  PR #25 documents this.

**Comment by eppolito** [comment]
Thanks for addressing this!  Still seems slightly weird to me, but if this is the convention best to go with it.
