### ISSUE TITLE
How to get the list of all submatches?

### ISSUE THREAD

**Issue by Munksgaard** [haskell-hvr/regex-tdfa#18]
There are a lot of helpful examples in the README, but I cannot figure out how to get the list of all submatches. I thought it would be something like `a =~ b :: [(String, String, String, [String])]`, but that does not seem to work for me.

**Comment by yutotakano** [comment]
I believe you can cast it to `[[String]]` to get a list of lists containing the full match and submatches for each one. From there, perhaps a `concat . map tail` would do.
