### ISSUE TITLE
Consider using package enummapset

### ISSUE THREAD

**Issue by Mikolaj** [haskell-hvr/regex-tdfa#6]
Moving over old issue. :)

https://github.com/ChrisKuklewicz/regex-tdfa/issues/19

**Comment by andreasabel** [comment]
I looked at this issue. The PR https://github.com/ChrisKuklewicz/regex-tdfa/pull/20 isn't organized well, mixing whitespace and other changes with the refactoring in one commit, so I do not know whether one cannot cherry-pick the commit easily.

Is it worth doing this refactoring?  I mean, _never change a running system_.  The hand-rolled reimplementations in `regex-tdfa` are thin wrappers of `containers`, so, likely correct.

The point of the refactoring would be to add `regex-tdfa` as a user to `enummapset`.  Is there still interest (and willingness to contribute a PR from the `enummapset` maintainers' side, @Mikolaj )?
